name: figma_shopping_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  awesome_extensions: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: fonts/SF-Pro-Text-Semibold.otf
          weight: 600
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Medium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Thin.ttf
          weight: 100


flutter_native_splash:
  color: "#9775FA"
  color_dark: "#1B262C"
  image: assets/splash_screen_light.png
  image_dark: assets/splash_screen_dark.png
  android_12:
    image: assets/splash_icon.png
